config/routes.rb
OldFarts::Application.routes.draw do
  root to: 'home#index'
  

  resources :users
    
  resources :rounds
  resources :sessions, :only => [:new, :create, :show, :destroy]

  

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :rounds
	has_many :users, :through => :rounds
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
	
end

app/models/round.rb
class Round < ActiveRecord::Base
	
	belongs_to :users
	belongs_to :courses

	validates_presence_of :score, :winnings, :course_id, :user_id

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :rounds
	has_many :courses, :through => :rounds
	has_and_belongs_to_many :groups

	validates_presence_of :first_name, :last_name, :email, :password
	validates_uniqueness_of :email
	validates :email, :format => {:with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}
	validates :password, :length => {:minimum => 5}


	def full_name
		self.first_name + " " + self.last_name
	end

	def winnings
		self.rounds.pluck(:winnings)
	end

	def net_winnings
		# calculate net money gained 
		self.winnings.reduce(:+)
	end

	def rounds_played
		# total rounds played
		self.rounds.count
	end

	def worst_loss
		# show round with most money lost
		self.winnings.min
	end

	def biggest_win
		# show round with most money won
		self.winnings.max
	end

	def avg_winnings_per_round
		# calculate total winnings / rounds played
		self.net_winnings / self.rounds_played
	end

	def avg_win
		# averge amount of money you win, when you win money
		gains = self.winnings.map { |i| i > 0 }
		gains.reduce(:+) / gains.count
	end

	def avg_loss
		# average amount of money you lose, when you lose money
		losses = self.winnings.map { |i| i < 0 }
		losses.reduce(:+) / losses.count		
	end

	def status
		# determined by consecutive rounds of either winning or loosing money
		# types: ice_cold, cold, steady, warming up, hide your wallets
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

	def new
	end

	def create
	end

	def show
	end

	def update
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:id] = @user.id
			render :js => "window.location = '/users/show'"
		else
			if !@user
				render :json => { :error => "Invalid Email" }, :status => 422
			elsif @user && !@user.authenticate(params[:session][:password])
				render :json => { :error => "Invalid Password" }, :status => 422
			elsif params[:session][:email].blank? || params[:session][:password].blank?
				render :json => { :error => "Please fill in all fields" }, :status => 422
			end
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :json
	
	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			session[:id] = @user.id
			render :js => "window.location = '/users/show'"
		else
			errors = @user.errors.full_messages.join("<br>")
			render :json => { :error => errors }, :status => 422
		end
	end

	def show
		@user = current_user
		@user = User.find(@user.id)
	end

	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			render :js => "window.location = '/users/show'"
		else
			render :json => { :error => @user.errors.full_messages.join("<br/>") }, :status => 422
		end
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :handicap)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def signed_in?
		return true if session[:id]
	end

	def current_user
		if session[:id]
			@current_user ||= User.find(session[:id])
		end
	end
end

app/views/home/index.html.erb
<% if current_user %>
	<h1>Welcome Back</h1>
<% else %>
	<h1>Welcome, Sign Up to Join!</h1>
	<%= link_to "Sign Up", new_user_path, :class => "button" %>
	<%= link_to "Log In", new_session_path, :class => "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "OldFartsGolf" %></title>
    <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/foundation/5.0.2/css/foundation.css">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <header>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "OldFartsGolf", root_path%></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        
        <% if current_user %>
          <ul class="left">
            <li><%= link_to "Dashboard" %></li>
            <li><%= link_to "Profile", :controller => "users", :action => "show", :id => current_user.id %></li>
          </ul>
          <ul class="right">  
            <li><%= link_to "Welcome, #{current_user.first_name}!", :controller => "users", :action => "show", :id => current_user.id %></li>
            <li><%= link_to "Logout", session_path(session), :method => :delete %></li>
          </ul>
          <% else %>
            <ul class="right">  
              <li><%= link_to "Log In", new_session_path %></li>
              <li><%= link_to "Sign Up", new_user_path %></li>
            </ul>
          <% end %>

      </section>
    <nav>
  </header>
  <body>
    <div class="row">
      <div class="small-11 small-centered columns">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/users/edit.html.erb
<div id="edit-errors"></div>
<div id="edit-form" class="small-9 columns center">
<%= form_for @user, :html => { :action=> :update }, :remote => true do |f| %>
	<p><%= f.text_field :first_name, :autofocus => true %></p>
	<p><%= f.text_field :last_name %></p>
	<p><%= f.email_field :email %></p>
	<p><%= f.text_field :password, :placeholder => "Password" %></p>
	<p><%= f.text_field :password_confirmation, :placeholder => "Re-enter Password" %></p>
	<p><%= f.number_field :handicap %></p>

	<%= f.submit "Submit", :class=> "button" %>
	<%= link_to "Cancel", :back, :class => "button alert" %>
<% end %>
</div>

app/views/users/new.html.erb
<h2>Sign Up!</h2>
<div id="signup-errors"></div>
<div id="signup-form" class="small-9 columns center">
<%= form_for @user, :url => users_path, :remote => true do |f| %>
	<p><%= f.text_field :first_name, :placeholder => "First Name", :autofocus => true %></p>
	<p><%= f.text_field :last_name, :placeholder => "Last Name" %></p>
	<p><%= f.email_field :email, :placeholder => "example@email.com" %></p>
	<p><%= f.password_field :password, :placeholder => "Create Password (min: 5 characters)" %></p>
	<p><%= f.password_field :password_confirmation, :placeholder => "Re-enter Password" %></p>
	<p><%= f.number_field :handicap, :placeholder => "Current Handicap (if applicable)" %></p>

	<%= f.submit "Submit", :class=> "button" %>
	<%= link_to "Cancel", root_path, :class => "button alert" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="small-9 columns user-profile">
		<h2><%= @user.full_name %>  <%= link_to '', edit_user_path(@user), :class => "fa fa-pencil-square-o" %></h2>
		<span><%= @user.email %></span>
		<hr>
		<div id="profile-stats">
			<ul class="breadcrumbs">
				<li class="golf-stats"><a class="active">Playing Stats</a></li>
			  <li class="betting-stats"><a>Betting Stats</a></li>
			</ul>
		</div>
		<table class="betting-table">
		  <tbody>
		  	<th>Your Betting Statistics</th>
		    <tr>
		      <td>Rounds Played</td>
		      <td><%= @user.rounds_played %></td>
		    </tr>
		    <tr>
		      <td>Net Winnings</td>
		      <td><i class="fa fa-usd"></i><%= @user.net_winnings %></td>
		    </tr>
		    <tr>
		      <td>Winnings Per Round</td>
		      <td><i class="fa fa-usd"></i><%=  %></td>
		    </tr>
		    <tr>
		      <td>Biggest Win</td>
		      <td><i class="fa fa-usd"></i><%= %></td>
		    </tr>
		    <tr>
		      <td>Worst Loss</td>
		      <td><i class="fa fa-usd"></i><%= @user.worst_loss %></td>
		    </tr>
		    <tr>
		      <td>Avg Win</td>
		      <td><i class="fa fa-usd"></i><%=  %></td>
		    </tr>
		    <tr>
		      <td>Avg Loss</td>
		      <td><i class="fa fa-usd"></i><%=  %></td>
		    </tr>
		  </tbody>
		</table>
		<table class="golf-table">
			<th>Your Playing Statistics</th>
			<tr>	
				<td>golf table</td>
			</tr>
		</table>
	</div>
	<div class"small-2 columns">
		<button class="new-round success">
			<i class="fa fa-plus"></i>
			New Round
		</button>
	</div>
</div>